image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup environment
    init: |
      sudo apt-get update && sudo apt-get install -y \
      git \
      curl \
      cp .streamlit/secrets.toml.example .streamlit/secrets.toml
      echo "Python version:"
      python3 --version
      echo "Git version:"
      git --version
  - name: Create Nillion environment
    init: |
      echo "Nilup version:"
      nilup -V
    command: |
      cd nillion-python-starter/
      nilup install latest
      nilup use latest
      nilup init
      sh telemetry.sh
      source /home/gitpod/.bashrc && export PATH=$PATH:/home/gitpod/.nilup/sdks/latest
      nillion -V
      pip install --upgrade pip
      pip install -r requirements.txt
      cd quickstart/nada_quick_start_programs
      nada build
      cd ..
      cd ..
      echo "✅ Compiled all programs to binary (.nada.bin) in target/ directory"
      echo "🖥️ Check out Nada programs in src/ directory"
      echo "🧪 Check out Nada program test files in tests/ directory"
      echo "👇 Run the addition program with the addition_test file with the 'nada run' command"
      nillion-devnet

